server:
  port: 8086

jwt:
  key: ${JWT_KEY:KAKAROTTO-DOES-KAME-HAME-HA-AND-GENKIDAMA-AND-KIENSAN}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: password
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:192.168.12.196}:${DB_PORT:5432}/${DB_NAME:test}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: postgres
  cloud:
    aws:
      region: ${AWS_REGION:us-east-1}
      #      endpoint: ${AWS_ENDPOINT_HOST:localhost}
      s3:
        processing-bucket: ${AWS_S3_BUCKET_NAME:videoprocessing-fiap}
      sqs:
        processing-queue-name: ${QUEUE_NAME:trigger_processing}
        update-process-status-queue-name: ${SQS_UPDATE_PROCESS_QUEUE_NAME:update_process}
      sns:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  access:
    key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN}