apiVersion: v1
kind: Service
metadata:
  name: svc-testing
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "video-processor-rest-api-lb"
spec:
  type: LoadBalancer
  ports:
    - port: 8086
  selector:
    app: video-processor-rest-api